export const ActionTypes = {
  ADD_HABIT: "ADD_HABIT",
  OPEN_D : "OPEN_D",
  CLOSE_D : "CLOSE_D",
  CHANGE_STATUS :"CHANGE_STATUS",
  MARK_DONE :"MARK_DONE",
  MARK_NOT_DONE : "MARK_NOT_DONE",
  MARK_NONE :"MARK_NONE",
  DELETE_HABIT : "DELETE_HABIT",

};
